//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarketing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avaliacao
    {
        public int IdAvaliacao { get; set; }
        public int IdEmpresa { get; set; }
        public int IdConsumidor { get; set; }
        public int ValorAvaliacao { get; set; }
        public System.DateTime DataAvaliacao { get; set; }
    
        public virtual Consumidor Consumidor { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
